version: '3'
services:
    web:
        build: .
        restart: always
        env_file: 
            - .env
        depends_on: 
            - db

    db:
        image: postgres
        restart: always
        env_file: 
            - .env
